version: "3.8"
services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - NODES_EXCLUDE="[]"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
      - ./inputs:/home/node/inputs
      - ./outputs:/home/node/outputs
      - ./prompts:/home/node/prompts

volumes:
  n8n_data:


